[package]
name = "phoinix-cli"
description = "PHOINIX command-line application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "phoinix"
path = "src/main.rs"

[dependencies]
phoinix-core = { workspace = true }
phoinix-block = { workspace = true }
phoinix-device = { workspace = true }
phoinix-volume = { workspace = true }
phoinix-fs = { workspace = true }
phoinix-fs-ntfs = { workspace = true }
phoinix-health = { workspace = true }
phoinix-recovery = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
flate2 = "1"
sha2 = { workspace = true }
hex = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
